# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-27 19:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AwayStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_appearences', models.IntegerField(verbose_name='game appearences')),
                ('minutes_played', models.IntegerField(verbose_name='minutes played')),
                ('goals_scored', models.IntegerField(verbose_name='goals scored')),
                ('assists', models.IntegerField(verbose_name='assists')),
                ('yellow_cards', models.IntegerField(verbose_name='yellow cards')),
                ('red_cards', models.IntegerField(verbose_name='red cards')),
                ('shots_per_game', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='shots per game')),
                ('pass_success_percentage', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='pass success percentage')),
                ('aerials_won', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='aerials won')),
                ('man_of_the_match', models.IntegerField(verbose_name='man of the match')),
                ('away_rating', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='overall_rating,')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=200)),
                ('votes', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='DefensiveStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tackles_per_game', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='tackles per game')),
                ('interceptions_per_game', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='interceptions per game')),
                ('fouls_per_game', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='fouls per game')),
                ('offsides_won_per_game', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='offsides won per game')),
                ('clearances_per_game', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='clearances per game')),
                ('dribbled_past_per_game', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='dribbled past per game')),
                ('outfielder_block_per_game', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='outfielder block per game')),
                ('own_goals', models.IntegerField(verbose_name='own goals')),
                ('defensive_rating', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='defensive rating,')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='HomeStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_appearences', models.IntegerField(verbose_name='game appearences')),
                ('minutes_played', models.IntegerField(verbose_name='minutes played')),
                ('goals_scored', models.IntegerField(verbose_name='goals scored')),
                ('assists', models.IntegerField(verbose_name='assists')),
                ('yellow_cards', models.IntegerField(verbose_name='yellow cards')),
                ('red_cards', models.IntegerField(verbose_name='red cards')),
                ('shots_per_game', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='shots per game')),
                ('pass_success_percentage', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='pass success percentage')),
                ('aerials_won', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='aerials won')),
                ('man_of_the_match', models.IntegerField(verbose_name='man of the match')),
                ('home_rating', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='overall_rating,')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='OffensiveStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_passes_per_game', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='key passes per game,')),
                ('dribbles_per_game', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='dribbles per game,')),
                ('fouled_per_game', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='fouled per game,')),
                ('offsides_per_game', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='offsides per game,')),
                ('dispossessed_per_game', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='dispossessed per game,')),
                ('badcontrol_per_game', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='badcontrol per game,')),
                ('offensive_rating', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='offensive rating,')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='PassingStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passes_per_game', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='passes per game,')),
                ('crosses_per_game', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='crosses per game,')),
                ('longballs_per_game', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='longball per game,')),
                ('throughballs_per_game', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='throughballs per game,')),
                ('passing_rating', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='passing rating,')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200, verbose_name='question')),
                ('slug', models.SlugField(default=b'slug_text', unique_for_date=b'pub_date', verbose_name='slug')),
                ('keywords', models.CharField(max_length=100, null=True, verbose_name='keywords')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='date published')),
                ('question_type', models.IntegerField(choices=[(1, 'IDEA'), (2, 'CATALOGUE'), (3, 'PROJECT')], default=1, verbose_name='question Type')),
                ('is_featured', models.BooleanField(default=False, verbose_name='is_featured')),
                ('likecount', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_appearences', models.IntegerField(verbose_name='game appearences')),
                ('minutes_played', models.IntegerField(verbose_name='minutes played')),
                ('goals_scored', models.IntegerField(verbose_name='goals scored')),
                ('assists', models.IntegerField(verbose_name='assists')),
                ('yellow_cards', models.IntegerField(verbose_name='yellow cards')),
                ('red_cards', models.IntegerField(verbose_name='red cards')),
                ('shots_per_game', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='shots per game')),
                ('pass_success_percentage', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='pass success percentage')),
                ('aerials_won', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='aerials won')),
                ('man_of_the_match', models.IntegerField(verbose_name='man of the match')),
                ('overall_rating', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='overall_rating,')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='date published')),
            ],
        ),
        migrations.AddField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pools.Question'),
        ),
    ]
